[package]
name = "cargo-strict"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]
edition = "2024"

[dependencies]
walkdir = "2"
memchr = "2"
md5 = "0.8"
difflib = "0.4"
chrono = "0.4"
